Fix pipeline for docs

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -12,7 +12,7 @@ permissions:
   id-token: write
 
 jobs:
-  docker:
+  publish-pipe:
     runs-on: ubuntu-latest
 
     steps:
@@ -48,6 +48,16 @@ jobs:
 
       - name: Generate all documentation
         run: make generate-docs
+        env:
+          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.vars.outputs.TAG }}
+
+      - name: Verify documentation version
+        run: |
+          DOC_VERSION=$(grep '"version":' docs/openapi.json | awk -F '"' '{print $4}')
+          if [ "$DOC_VERSION" != "v${{ steps.vars.outputs.TAG }}" ]; then
+            echo "::error::Documentation version '$DOC_VERSION' does not match tag 'v${{ steps.vars.outputs.TAG }}'."
+            exit 1
+          fi
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
